### ISSUE TITLE
Import problem

### ISSUE THREAD

**Issue by Vincz** [odedglas/react-linear-gradient-picker#1]
To import, I have to do:

```
import Gradient from "react-linear-gradient-picker";  
const {GradientPicker, AnglePicker} = Gradient;
```

because 

`import {GradientPicker, AnglePicker} from "react-linear-gradient-picker";`

doesn't work.

**Comment by odeadglaz** [comment]
Hey, Thanks for the report, Was my bad :).
Please checkout 1.0.4, Should be solved.
