### ISSUE TITLE
Delete color

### ISSUE THREAD

**Issue by robba86** [odedglas/react-linear-gradient-picker#11]
Hello, thanks for the good work with this :) But i found a bug i think.

When adding a new color and its _still selected_ and choose to delete that color, i get this error:

```
src/components/GradientPicker/index.js:33
  30 | 
  31 | const getPaletteColor = (palette, id) => {
  32 | 	const color = palette.find(color => color.id === id);
> 33 | 	return { ...color, offset: Number(color.offset) };
  34 | };
  35 | 
  36 | const GradientPicker = ({
```

```
src/components/GradientPicker/index.js:107
  104 | 	handlePaletteChange(updatedPalette);
  105 | };
  106 | 
> 107 | const colorPicker = () => {
      | ^  108 | 	const { color, opacity } = getPaletteColor(palette, activeColorId);
  109 | 
  110 | 	const props = {
```

```
src/components/GradientPicker/index.js:148
  145 | 				onDeleteColor={handleColorDelete}
  146 | 				onDragStart={onStopDragStart}
  147 | 			/>
> 148 | 			{colorPicker()}
  149 | 		</div>
  150 | 	);
```

Using state and manipulating it with:
```javascript
const remove = (id) => {
	const updatedPalette = palette.filter((color) => color.id !== id);
	onPaletteChange(updatedPalette); // onPaletteChange is setPalette
};
```

jsx:
```jsx
<ul>
	{palette.map((item) => (
		<li>
			{item.id} {item.color}{' '}
			{item.id !== 1 && item.id !== 2 && (
				<div onClick={() => remove(item.id)}>Delete</div>
			)}
		</li>
	))}
</ul>
```

**Comment by odeadglaz** [comment]
Could not reproduce it, when you add new color it will become active (selected) immediately, could not find any issue with removing it afterward. can you specify you case a bit better in order to reproduce it?

**Comment by robba86** [comment]
![Peek 2020-08-20 23-56](https://user-images.githubusercontent.com/16581922/90829811-c625ce80-e340-11ea-95de-995f28563522.gif)

**Comment by robba86** [comment]
The offset property is undefined becouse i deleted it... the function `getPaletteColor` is depending on the `offset` property but when the "linear-color-stop-selector" is selected and i update my state with the new "linear-color-stop-selectors" this happens.

Using: "react-linear-gradient-picker": "^1.1.2"

This is my code:
```
import PropTypes from 'prop-types';
import React, { useState } from 'react';
import { SketchPicker } from 'react-color';
import { GradientPickerPopover } from 'react-linear-gradient-picker';
import styled from 'styled-components';

const StyledGradientColorPicker = styled.div`
	.overlay,
	.popover {
		position: relative;
		box-shadow: none;
	}
	.overlay,
	.trigger {
		display: none;
	}
`;

/**
 * (c) https://stackoverflow.com/questions/21646738/convert-hex-to-rgba
 */
function addOpacityToHex(hex, a = 1) {
	let c;
	if (/^#([A-Fa-f0-9]{3}){1,2}$/.test(hex)) {
		c = hex.substring(1).split('');
		if (c.length === 3) {
			c = [c[0], c[0], c[1], c[1], c[2], c[2]];
		}
		c = '0x' + c.join('');
		return (
			'rgba(' +
			[(c >> 16) & 255, (c >> 8) & 255, c & 255].join(',') +
			',' +
			a +
			')'
		);
	}
	if (/rgb\((\d{1,3}), (\d{1,3}), (\d{1,3})\)/.test(hex)) {
		/** RGB color */
		return hex.replace('rgb', 'rgba').replace(')', `, ${a})`);
	}
	throw new Error('Bad Hex');
}

const WrappedSketchPicker = ({ onSelect, ...rest }) => {
	return (
		<SketchPicker
			{...rest}
			color={addOpacityToHex(rest.color, rest.opacity)}
			onChange={(c) => {
				onSelect(c.hex, c.rgb.a);
			}}
		/>
	);
};

WrappedSketchPicker.propTypes = {
	onSelect: PropTypes.func,
};

export const GradientColorPicker = ({
	palette,
	onPaletteChange,
	angle,
	setAngle,
	showAnglePicker,
	width,
	maxStops,
	paletteHeight,
}) => {
	const [open, setOpen] = useState(true);

	const remove = React.useCallback(
		(id) => {
			const updatedPalette = palette.filter((color) => color.id !== id);
			onPaletteChange(updatedPalette);
		},
		[onPaletteChange, palette]
	);

	return (
		<StyledGradientColorPicker>
			<GradientPickerPopover
				open={open}
				setOpen={setOpen}
				angle={angle}
				setAngle={setAngle}
				showAnglePicker={showAnglePicker}
				width={width}
				maxStops={maxStops}
				paletteHeight={paletteHeight}
				palette={palette}
				onPaletteChange={onPaletteChange}
			>
				<WrappedSketchPicker />
			</GradientPickerPopover>

			<ul>
				{palette.map((item) => (
					<li>
						<div>{item.id}</div>
						<div>{item.color}</div>
						<button
							disabled={item.id === 1 || item.id === 2}
							onClick={() => remove(item.id)}
						>
							Remove
						</button>
					</li>
				))}
			</ul>
		</StyledGradientColorPicker>
	);
};

GradientColorPicker.propTypes = {
	palette: PropTypes.array,
	onPaletteChange: PropTypes.func,
	angle: PropTypes.number,
	setAngle: PropTypes.func,
	showAnglePicker: PropTypes.bool,
	width: PropTypes.number,
	maxStops: PropTypes.number,
	paletteHeight: PropTypes.number,
};
```

**Comment by robba86** [comment]
CodeSandbox: https://codesandbox.io/s/offset-undefined-when-delete-linear-color-stop-selector-f4tuv

**Comment by odeadglaz** [comment]
Gotya, so you're trying to mutate the palette, not via the `GradientPicker` itself, whether from another controlled action.

Currently, this component does not support controlled actions, meaning all the manipulation should be done via the `GradientPicker` itself, e.g for stop removal, you would have to drop the color thumb away from the palette bar ( up or down ).

This also applies to try to mutate the palette directly and not via the component.

the `setPalette` acts as a proxy for the component to be able to mutate the given initial palette.

Why would you manually try to remove stop colors from a custom action and not the component itself? would help if you can specify what you're trying to achieve :)

**Comment by odeadglaz** [comment]
Closed due to inactivity, if it's still relevant, feel free to re-open it 🎉

**Comment by manugb** [comment]
If use a setTimeout 0 when calling setPalette I am having this issue with the offset.
I guess it is from setActiveColorId, it forces a re-render in the GradientPicker but palette still didnt update.
I believe the re-render should come from changes in palette... or you should handle palette changes locally using state and dispatch them outside from the comp. 
Palette comes from props so if handlePaletteChange takes it time to update it, the component will run with old palette and in getPaletteColor wont find the color because palette is still outdated

**Comment by manugb** [comment]
It works fine in 1.1.0

It starts crashing from 1.1.1, the problem is the comp is looking for a color in palette but palette is still not updated and that color still dont exist in the array.
I am reproducing it by adding a stop and calling a setTimeout(() => setPalette(palette), 0) in handlePaletteChange
