### ISSUE TITLE
Having #000000 and changing it to opacity 0 app craches

### ISSUE THREAD

**Issue by robba86** [odedglas/react-linear-gradient-picker#12]

**Comment by robba86** [comment]
i have seen in other libs that it uses transparent as an valid value instead of #00000000 or rgba(0,0,0,0).. idk if there is something to it?

**Comment by robba86** [comment]
Using with `SketchPicker`, inside the `addOpacityToHex` add:

```js
if (hex.toLowerCase() === 'transparent') {
	// return '#00000000';
	return 'rgba(0, 0, 0, 0)';
}
```
:)

**Comment by odeadglaz** [comment]
So after considering this, and as you said there might be some libraries that would consider Transparent as valid HEX, others might say different.

I simplified the SketchPicker story to work with `RBB` format instead, which avoids this whole collision and will keep this library agnostic to the Transparent case.

Please keep in mind that this library tries to stay as close as possible to the `SVG Linear gradient` element ( which do not support hex with opacity / RGBA strings. ) 

Hope this helps. :)

**Comment by odeadglaz** [comment]
Closed due to inactivity, if it's still relevant, feel free to re-open it 🎉
