### ISSUE TITLE
onPaletteChange is not triggered when clicking on a stops

### ISSUE THREAD

**Issue by liorsharabi** [odedglas/react-linear-gradient-picker#15]
when i'm clicking on the stops it's not triggering the onPaletteChange.
(when i'm moving them it works)
is there another why to do something when the user click on the stops?

it seems like in the doc that it should trigger onPaletteChange
![image](https://user-images.githubusercontent.com/22159686/107199817-8abab180-69ff-11eb-98b9-8bc3a34b876e.png)

**Comment by odeadglaz** [comment]
Hey,
The `onPaletteChange` event is deriven form 2 sources:
1. Stop drag - Meaning you selected a stop, and dragged him.
2. Color select - Meaning you manually selected a color from the picker -
![image](https://user-images.githubusercontent.com/49120070/107271960-a9e42e00-6a55-11eb-998e-d4b292373e68.png)

When u click on a given stop, It only changes the `active` color, there is no palette change.

Are you trying to intercept a stop click - e.g an `activeColorChange` event?

**Comment by odeadglaz** [comment]
Lemme know if it still remains an open question 👍
