### ISSUE TITLE
How to make the color slider change on simple click?

### ISSUE THREAD

**Issue by Virthuss** [odedglas/react-linear-gradient-picker#16]
It seems now that the color is changing when clicking and dragging, but not on simple click ( which seems to work with the "normal" color picker ) on the small color bar ( not the big square which is working fine ). 

Am I doing something wrong? If not, how to make this clickable AND draggable?
Thanks in advance.

**Comment by odeadglaz** [comment]
Hey, I tried to play with it and couldn't reproduce, it seems reactive to any click i made on the bottom small color bar, could you attach a screen short extending your case?

**Comment by Virthuss** [comment]
Seems like the bug was linked to the library I used for the wrapper. My bad.
