### ISSUE TITLE
Getting the Currently Selected Stop

### ISSUE THREAD

**Issue by shubymao** [odedglas/react-linear-gradient-picker#17]
Is there a way to get the currently selected stop to be used when highlighting etc? Like an id indicating which pallet array index is selected. Thanks in advance.

**Comment by odeadglaz** [comment]
Currently, there isn't, I'll try to add support for this one in the visible future hopefully :)

**Comment by odeadglaz** [comment]
Added support for it over `1.2.0` -> https://github.com/odedglas/react-linear-gradient-picker/commit/19224d8d1cedde526f77207873020d1d90f477c2

👍
