### ISSUE TITLE
Requires node global polyfill, not compatible with Vite

### ISSUE THREAD

**Issue by penx** [odedglas/react-linear-gradient-picker#23]
When trying to use this library from within a Vite application, you get the error

> Uncaught ReferenceError: global is not defined

This seems to be the same as this error against another library:

> global is a node builtin which libraries should not depend on

https://github.com/vitejs/vite/discussions/5912

This seems to stem from the usage of webpack to produce the dist version.

To recreate:

1. `yarn create vite` and select react-ts
2. `yarn add react-linear-gradient-picker`
3. implement example code from react-linear-gradient-picker readme
4. `yarn dev` and open localhost:3000
5. See error in browser console

**Comment by odeadglaz** [comment]
I reproduced it and was able to solve it, Mind you validate it does fix your usecase? 🙏 

Thanks for your report anyway :)

**Comment by odeadglaz** [comment]
Closed due to inactivity. Let me know if u still encounter issues.
