### ISSUE TITLE
Removing color stop problem

### ISSUE THREAD

**Issue by Vincz** [odedglas/react-linear-gradient-picker#3]
On[ this example](https://odedglas.github.io/react-linear-gradient-picker/?path=/story/gradient-picker--react-color-picker)

If we try to remove the first color stop, we get an error

**Comment by Vincz** [comment]
Error is : `Cannot read property 'offset' of undefined`

**Comment by odeadglaz** [comment]
Hey @Vincz ! Thanks for your awesome reports!
I was able to reproduce, It will be solved on next release.
