### ISSUE TITLE
Preview with single stop

### ISSUE THREAD

**Issue by Vincz** [odedglas/react-linear-gradient-picker#4]
Hey @odedglas !
First of all, the new version is awesome! Really clean, and the popover is really great! You did a great job !

My last use case is that I allow users to select either a gradient or ... a single color (as a gradient with only one stop). I'd like the preview to be able to render it as a plain color. 
I think the correct repository would be `linear-gradient-parser` for this and just update the `asBackground` function to check if there is only one stop, and if so, return just the color.

**Comment by odeadglaz** [comment]
Indeed my friend, Sounds lovely!

**Comment by odeadglaz** [comment]
Solved at 1.1.8 :)
