### ISSUE TITLE
onSelect is missing

### ISSUE THREAD

**Issue by aish058** [odedglas/react-linear-gradient-picker#7]
Hi, I tried writing the wrappedsketchpicker in the same way as mentioned [here](https://www.npmjs.com/package/react-linear-gradient-picker#gradient-picker-usage), I am using VSCode for my project , on writing 

<WrappedSketchPicker {...{
                width: 200,
                disableAlpha: true 
              }} />

 it gives the following error 

Property 'onSelect' is missing in type '{}' but required in type '{ [x: string]: any; onSelect: any; }'.ts(2741)

is there something additional that i need to do?
even on simply copy-pasting the code , it isnt working, any help?

**Comment by odeadglaz** [comment]
Not quite sure what you mean, you check out this example over here: https://odedglas.github.io/react-linear-gradient-picker/?path=/story/gradient-picker--popover-with-angle-picker.

I cannot reproduce it on the storybook.

Can you check the link I sent and validate?

**Comment by aish058** [comment]
Sir, It looks fine in the link you sent, 
I am also trying to write it using react-color, somehow it isnt working for me. 


import React, { useState } from 'react';
import { SketchPicker } from 'react-color';
import { GradientPicker } from 'react-linear-gradient-picker';
const WrappedSketchPicker = ({ onSelect, ...rest }) => (
    <SketchPicker {...rest} onChange={c => {
        onSelect(c.hex, c.rgb.a );
    }}/>
);
const App = () => {
    const [palette, setPalette] = React.useState([
        { offset: '0.00', color: '#EEF10B' },
        { offset: '0.49', color: '#D78025' },
        { offset: '1.00', color: '#7E20CF' }
    ]);
    return (
        <GradientPicker {...{
            width: 320,
            paletteHeight: 32,
            palette,
            onPaletteChange: setPalette
        }}>
              <WrappedSketchPicker {...{              //this line
                width: 200,
                disableAlpha: true
              }} />
        </GradientPicker>
    );
};
export default App;



this is the basic reduced version of what i wrote, and the error occurs in 'this line'.  it is saying onSelect function is missing in  {width: 200, disableAlpha:true} . I am not pointing out any issue in the library, just needed some help in using it.  😄

**Comment by aish058** [comment]
Is there a way to fix the position of the first and last colorStops to start and end of the color picker?

**Comment by odeadglaz** [comment]
So the `onSelect` is provided to the given color picker component in your case `WrappedSketchPicker` by the `GradientPicker` component.

Regarding the position not quite sure what you mean, by default, it will have the pallet stop values e.g if you set it with 2 stops, for 0 and 100 you should get ->

![image](https://user-images.githubusercontent.com/49120070/81837560-af0b5f80-954d-11ea-9536-5e7943393375.png)

**Comment by aish058** [comment]
I mean I want the ones set on 0% and 100% to not move. Is there a way to do
that??

**Comment by odeadglaz** [comment]
Not by component property.
You can achieve that by custom implementing the `setPallete` method, which configures the palette as you need it.

**Comment by odeadglaz** [comment]
Closed due to inactive, if you have any question remaining, you can open another concert issue.

**Comment by aish058** [comment]
Hi!! is there some way i can make the newly created stop on the palette as
the active stop??
