### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by aish058** [odedglas/react-linear-gradient-picker#8]
Is there a way to call the onSelect function or select a colorstop from outside the gradient picker component? and not by clicking on the stop on the picker?
i need to select a colorstop from outside the palette, indirectly and change its CSS. Can anyone please help?

**Comment by aish058** [comment]
i want to decide which colorstop is active at the moment, is there a provision or a way to do that? how can i control active state of colorstops from outside the palette?

**Comment by odeadglaz** [comment]
Currently, it does not support `controlled` mode. that could be added as feature :)
