### ISSUE TITLE
AnglePicker dragging not working

### ISSUE THREAD

**Issue by Muini** [odedglas/react-linear-gradient-picker#9]
Hi !

I added AnglePicker to my custom color picker (using react-color) and I got this error : 
![image](https://user-images.githubusercontent.com/6160740/87305625-cda5bc80-c4e4-11ea-8c4d-b2a709232a51.png)

Code is minified so I cannot get clearer view than this. I'm using require to import and not es6 import because my project is in typescript.

I can manually set the value and the knob is turning, but direct interaction will fire this error. Any ideas ? Thanks !

**Comment by odeadglaz** [comment]
Hey, I think it's yelling because your not passing the `setAngle` property.
Checkout out ur console tab, react prop types should alert you on that one.

If this doesn't help, could you attach your code usage snipper so I could get a look at how you render the `AnglePicker` component?

**Comment by Muini** [comment]
@odeadglaz Hi ! sorry late answer, this was indeed yelling because I was using the prop `onChange` instead of `setAngle` and this is because it's a bit confusing in the documentation : 
https://github.com/odedglas/react-linear-gradient-picker#angle-picke-usage
In the exemple it's using `onChange` and below, in the API it's `setAngle`, that's all !
Thanks for the help, finally it's just a small typo on the doc.

**Comment by odeadglaz** [comment]
I'll ensure to fix those docs, thanks for the report.

**Comment by odeadglaz** [comment]
Resovled.
